### ISSUE TITLE
Ad images sometimes grabbed

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#1]
Hello! I don't know if there's anything that you can do about this, but sometimes Instantgram Light grabs images or videos from advertisements that are blocked by my ad blockers and thus are invisible anyway. It also is sometimes grabbing the images from other posts on the timeline when viewing a post's comments on the timeline, [such as this view here](https://i.imgur.com/ulNVQAr.png).

Thanks so much for your time!

**Comment by ThinkBIG-Company** [comment]
New version is in preparing stay tuned

**Comment by ThinkBIG-Company** [comment]
New version released :smiling_face_with_three_hearts:
