### ISSUE TITLE
Stories no longer working

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#10]
Hello! We went a really long time without having any real issues, but unfortunately as of yesterday, stories of any kind no longer work. I get the standard 'did you try a post?' thing.

I've also been occasionally getting errors where it can't grab anything at all but it's pretty infrequent. I haven't figured out if there's anything I can do to fix it.

**Comment by ThinkBIG-Company** [comment]
Thank you for your message,
I have already noticed it myself.
I'm curious to see if I can develop a fix.

**Comment by ThinkBIG-Company** [comment]
Fixed
