### ISSUE TITLE
24.4.24 Feedback

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#12]
Hello! Some more info on the story situation.

So 4.24 and 4.09 don't work on stories. 3.28 still works on stories, which is weird, but that does mean its code might be useful to you somehow. It's worth noting that 3.28 un-mutes stories, which can be startling considering instagram videos are so frickin loud, and also it doesn't pause video stories like its settings say it does. Photos still pause correctly. Hope this helps you!

**Comment by ThinkBIG-Company** [comment]
Hello Orudeon,
i use the software for myself and have noticed that when I open up a profile and want to save the story highlights, errors occur.
When i open stories in the feed and want to save them, there are no problems. I don't know why you are having problems.
I will add another function where you can reset the settings, I totally forgot that this is also important.

Thanks for your support you are a great memeber and supporter!!!

**Comment by Orudeon** [comment]
That's really odd that it works on the timeline for you and not me. I also noticed stories saved on someone's profile often suffers errors even with version 3.28

**Comment by ThinkBIG-Company** [comment]
I think that depends on where you live, e.g. america or europe or somewhere else

**Comment by ThinkBIG-Company** [comment]
Hello again i have seen instagram again have changed their code for stories.

I need to rewrite the stroy parser to handle highlights and feed stories properly.

Thanks

**Comment by ThinkBIG-Company** [comment]
Hi, the new version is almost ready...
I still have to do some tests and if they are all positive then I will release a brand new version with some outstanding features.

Stay tuned...
