### ISSUE TITLE
Download is not working in 2024.06.11

### ISSUE THREAD

**Issue by joa77** [ThinkBIG-Company/instantgram-light#13]
When trying to use the download function it redirects to a page which says `Invalid 'data' parameter.`

Opening the images in a new tab works without any problems, but the filename is wrong

**Comment by ThinkBIG-Company** [comment]
Do you have a example url?
Which browser and browser version do you have and language?

**Comment by ThinkBIG-Company** [comment]
Fixed without needed update
Thanks for reporting
