### ISSUE TITLE
Instagram Stories can't be downloaded at all.

### ISSUE THREAD

**Issue by MaestroDaVinci** [ThinkBIG-Company/instantgram-light#14]
So i have been seeing a lot of problem with stories and for me the stories don't download at all. I tried on the latest versions of both Chrome and Firefox and with and without extensions, but it doesn't work at all. When i try to see any version this or even the normal nothing happens. I have tried to download the stories both on the timeline and in the profile and on both videos and pictures.

Here is one profile that i just tried
https://www.instagram.com/leverageredemption/

**Comment by Rocket3192** [comment]
Yep doesn't work on stories anymore, for both videos and pictures :)
Tested on Edge (chromium)

**Comment by ThinkBIG-Company** [comment]
Ok will look into this asap.

**Comment by ThinkBIG-Company** [comment]
I can not reproduce any issues on my side.
In the past i have noticed that instagram delivers different pages in different countries and that is why these strange errors occur.
A video would therefore help me a lot as I live in Germany and it is difficult for me to test many backends.

Thank you very much

**Comment by MaestroDaVinci** [comment]
I don't have a video, but for me at least i can't seem to understand what is happening for me. I tried in both Firefox and Chrome and whenever i open any story and try to use the this one nothing happens. There is no option showing up, there is no error, the story continues to play and no matter how many times i try to click on the bookmark nothing happens nothing at all.

**Comment by ThinkBIG-Company** [comment]
Have you tried to open the developer console and see whats happening or anything happening?

**Comment by ThinkBIG-Company** [comment]
Ok need this to reproduce your issue:
Operating System
Browser version
Browser Language
Your Country name

**Comment by MaestroDaVinci** [comment]
Bulgaria:
Firefox 127.0 (Windows 10), Language: en-US, instantgram-light: {"version":"2023.07.12","onlineVersion":"2023.06.23","lastVerification":1698135594495,"dateExpiration":1698157194495,"settings":[{"name":"Enable ads in posts:","value":true},{"name":"Change the filename format for downloads. The default format is as follows:","value":"{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}"}]} [debugger eval code:1:406](chrome://devtools/content/webconsole/debugger%20eval%20code)
Firefox 127.0 (Windows 10), Language: en-US, instantgram: {"version":"2024.06.11","onlineVersion":"2024.04.24","lastVerification":1719668308313,"dateExpiration":1719689908313}

Here is the info

**Comment by ThinkBIG-Company** [comment]
Ok i have done a little research and have now worked out the following possibility.

Please enter the following code in the F12 console:
```javascript
Object.keys(localStorage).forEach(e=>{e.startsWith("instantgram")&&(localStorage.removeItem(e),console.log(`Deleted key: ${e}`))}),console.log("All local storage keys starting with 'instantgram' have been deleted successfully.");
```

The following text should be there: "All local storage keys starting with 'instantgram' have been deleted successfully."

Then please download the latest versions for both bookmarklets:
[instantgram] v2024.06.11
[instantgram-light] v2023.07.12

Then it should work, unfortunately the settings are lost and have to be set again.

Thank you very much

Translated with DeepL.com (free version)

**Comment by RoyU16** [comment]
Hey, sorry if I'm missing something but instangram-light still shows as v2024.06.11 for me

Thanks

**Comment by ThinkBIG-Company** [comment]
Oh sorry my mistake,
the latest version of instantgram-light is v2024.06.11

i have updated my last post.

Thanks

**Comment by MaestroDaVinci** [comment]
I tried the solution on both Chrome and on Firefox and on both it doesn't work.

**Comment by ThinkBIG-Company** [comment]
Ok if you click on the bookmarklet direct on this page https://thinkbig-company.github.io/instantgram/ or this https://thinkbig-company.github.io/instantgram-light/ does it then open?
