### ISSUE TITLE
7/4 version seems completely nonfunctional

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#3]
I'm really excited to hear that you added so many things from my wishlist! However, It looks like Instagram has either thwarted your plans or something went awry as it seems the 7.4.2023 update isn't functional on any post, anywhere, regardless of type—reel, story, photo, video all throw [this error](https://i.imgur.com/MEnOnjR.png).

**Comment by Orudeon** [comment]
Hey! I got the 7/6 version when I came here to look for an update to this post. So far it's awesome! I love the photo select bubbles. It's even better than what I thought up (arrows to change). 

I definitely want to let you know that it seems like filename setting changes aren't taking. [Also the text is unreadable in dark mode](https://www.dropbox.com/s/odyyn4iafq3cgej/Wow_2023-07-04_16-30-27.png?dl=0), but toggling dark mode is an easy enough fix.

**Comment by ThinkBIG-Company** [comment]
Please try out the new version released

**Comment by ThinkBIG-Company** [comment]
The problem with colors still exists i can not handle all customized browsers like dark mode etc.

**Comment by Orudeon** [comment]
Okay, no worries about the colors! It's a pretty minor thing that only really applies when a setting needs changed anyway.
It looks like spaces don't work in the filename format, but that's okay, it's changeable now which is awesome! Big improvement.
Thanks so much for these fixes!
