### ISSUE TITLE
Post view nonfunctional

### ISSUE THREAD

**Issue by Orudeon** [ThinkBIG-Company/instantgram-light#5]
FB at it once again, Instantgram Light is nonfunctional whil eviewing individual posts such as by [going to this URL](https://www.instagram.com/p/CxivLLgML6a/). If you [view it from the profile](https://www.instagram.com/gamegrumps/), it still works.

All stories seem functional. Timeline remains nonfunctional, except for video posts.

Firefox 117.0.1 64-bit on windows 10, west coast USA.

**Comment by ThinkBIG-Company** [comment]
Working long time on a fix but nothing works.

Will try KI

**Comment by ThinkBIG-Company** [comment]
New update released should be fixed.
