### ISSUE TITLE
Can’t save stories or posts on newest Instagram update 

### ISSUE THREAD

**Issue by Breerosen11** [ThinkBIG-Company/instantgram-light#6]
I cannot save posts or stories properly on the newest update. Are you working on a fix?

**Comment by ThinkBIG-Company** [comment]
Yes but it is very hard

**Comment by ThinkBIG-Company** [comment]
Does stories saving generally not work?
Or what is your problem

**Comment by ThinkBIG-Company** [comment]
Sad news: Instagram has activated its HTML CSP system. I believe it has now been globally rolled out. I have most of the update ready, but the download button, which I'm sure many people love, is experiencing issues. Currently, Instagram sucks. I hope Meta gets destroyed soon.

Unfortunately, I need to change the functionality of the download button. 
I don't know how to do it yet. 
Perhaps anybody have some ideas?

**Comment by ThinkBIG-Company** [comment]
New update released should be fixed.
